### ISSUE TITLE
Assigning a projection

### ISSUE THREAD

**Issue by VictoriaStarnes** [mcolvin/Bluff-Lake-Project#1]
I have been unable to assign a projection to the Bluff Lake coordinates. I have tried using the kml file and remaking a shapefile from the poly_coordinates file.

One attempt is noted in lines 22-23 of the code. All other attempts were deleted.

**Comment by mcolvin** [comment]
@VictoriaStarnes See commit 3426ea3 that does the spatial projection, transformation, and some plotting. It should get you rolling again.

**Comment by mcolvin** [comment]
@VictoriaStarnes added a new commit 4240bc6 think yesterdays commit was not quite there.
