### ISSUE TITLE
lake area as a function of volume

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#10]
@VictoriaStarnes  can I also get a function that spits out lake area as a function of volume added to 2-functions.R

**Comment by mcolvin** [comment]
Also a function of board height over time where board height is an elevation?

**Comment by VictoriaStarnes** [comment]
I have added both new functions to the script. Check out the function for board height and let me know if it's what you wanted. I also included a variable so you could select the rotation of the drawdown.

**Comment by mcolvin** [comment]
@VictoriaStarnes  can you add in the script what the units are for volume and wse?

**Comment by VictoriaStarnes** [comment]
Added units to script
