### ISSUE TITLE
start date for simulations

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#11]
@VictoriaStarnes  Can you code in 3-load-and-clean.R the start date for the analysis. This is the day that we have wse values in the lake that we can use to link the model predicted wse to observed wse.

**Comment by mcolvin** [comment]
@VictoriaStarnes  You can also start looking at 6-analysis.R 

It is similar to the DO model in that it uses a differential equation solver. The first step is to get things up and make things are working by keeping it simple and then adding complexity.

**Comment by VictoriaStarnes** [comment]
Added start date. I put the comment above the logger section and at the beginning of the script.
