### ISSUE TITLE
hourly or daily discharge used for thresholds?

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#13]
@VictoriaStarnes  in the In_out_el() function in 2-function.R did you use daily discharge or hourly to figure out the thresholds that flow was in, out, and 0?

**Comment by mcolvin** [comment]
also, in the bays, if all boards are in and the radial arm gates are down then does water spill from all or is it just the end bays?

**Comment by VictoriaStarnes** [comment]
I used hourly discharge for the thresholds.

Water only comes over the two bays with boards.
