### ISSUE TITLE
more data wrangling

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#14]
@VictoriaStarnes can you wrangle the discharge data to merge with the Macon discharge data with the WSE data? 

Merging discharge_hourly with loggers in the 3-load-and-clean.r
Couple of things to make sure we get:
1. Are several fields to include: year, doy, hour, minute, wse, discharge (@macon, adjusted to watershed, in cms as units)
1. subset the data so it starts when we can start calibrating, should be the date you coded in.
1. make a field for 'continuous time' which is a fractional day starting at 0 for the first row of data an increasing fractinally for each hour and minute (i.e., 5:30 am would be 330 minutes in, 330/1440 = 0.2291667, the same time on the next day would be 1.2291667)

**Comment by VictoriaStarnes** [comment]
Done! I went ahead a re-coded a few things in the 3-load-and-clean script because I couldn't get them to run. I like using the lubridate package for time, so I added it to 1-global. I also changed the discharge/gauge rounding to 30 minute instead of hour intervals.
