### ISSUE TITLE
logger day of year

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#15]
@VictoriaStarnes  Can you look at day of year for logger data. January 1 2020 is coming in as doy=365, might apply to other years too. I expected it to be 1. might be something the conversion of dt on linen 126 of 3-load-and-clean.R

![image](https://user-images.githubusercontent.com/654215/93593162-2e37f680-f979-11ea-8d26-1ce2ef055af7.png)

**Comment by VictoriaStarnes** [comment]
Fixed it!
