### ISSUE TITLE
Take a look at WSE

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#16]
@VictoriaStarnes Can you take a look at the figure below. 
* How should the breaks be handled in the Cypress and Gauge WSEs? Some are a bit wonky, for example totally flipping in relative postion.
* I was expecting the Cypress and Gauage to look more like they do up to the vertical line, but the began to drift, is that an artifact or do they truly drift? They seem like they should line up or be pretty darn close

The figure code in the figures script, figure n==1

![image](https://user-images.githubusercontent.com/654215/93813454-c0a9f580-fc18-11ea-9017-4184543e8a51.png)

**Comment by VictoriaStarnes** [comment]
Okay, I cleaned up the data a bit. Let me know what you think. The loggers separate by about 0.1 m after September 14th 2019 until the old gauge logger was lost. This was when we had that weird jump in both loggers that we smoothed over. 

![image](https://user-images.githubusercontent.com/45180904/94069431-2f708580-fdb6-11ea-95db-df8c1b23e266.png)

**Comment by mcolvin** [comment]
@VictoriaStarnes Looks alot better, what do you think about that big dip in the black line in the middle, is it real?

**Comment by VictoriaStarnes** [comment]
We might have cameras out during that time, so I'll take a look. They might have left the gates open.

**Comment by VictoriaStarnes** [comment]
I believe it. The cameras show the water being pretty flashy at that point. It was at least as low as it is now. I looked through the raw data and it's a rapid but not immediate drop. The water dropping about a centimeter per hour. They probably had 1-2 gates open.

**Comment by mcolvin** [comment]
Ok, good to confirm.
