### ISSUE TITLE
WSE elevation for Intake

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#17]
@VictoriaStarnes  what is the elevation of the board top at intake?

**Comment by VictoriaStarnes** [comment]
68.800 meters

**Comment by mcolvin** [comment]
@VictoriaStarnes What is the width on the bays at the lake intake?

**Comment by VictoriaStarnes** [comment]
The intake is the same as one of the board bays in the main control structure. So there are two board sections which are 1.6764 meters each (metric conversion from blueprints).

**Comment by mcolvin** [comment]
@VictoriaStarnes great. Thanks
