### ISSUE TITLE
GAM for Intake~Macon

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#18]
@VictoriaStarnes  can you run some quick GAMS, just like you did for change in surface elevation but for the elevation of water at intake versus Macon? Basically I am curious if we can do a better job predicting the elevation of water at intake for periods where we do not have actual logger data?
Specifically can a GAM do a good job predicting the black line from the grey line where we don't have black line... I have a simple linear regression that does an ok job at it but the GAMs you did before might be better.

![image](https://user-images.githubusercontent.com/654215/94366492-540e7b00-009e-11eb-808a-7c1194a4eb8d.png)

**Comment by VictoriaStarnes** [comment]
Added the code for GAM model to the functions script.  R-sq.(adj) =  0.837

![image](https://user-images.githubusercontent.com/45180904/94487350-7ab7d900-01a6-11eb-814e-7ed8b640579c.png)

I also applied the model to the daily discharge values 1938-present. There were some funky outlier years, but I scaled the attached plot from 68-70.5m.

![image](https://user-images.githubusercontent.com/45180904/94487656-f6198a80-01a6-11eb-946d-9c35e2f9b1e9.png)

**Comment by VictoriaStarnes** [comment]
Whoops, the first plot is the fitted values for the model. This is the plot of the predicted values given discharge at Macon.

![image](https://user-images.githubusercontent.com/45180904/94488947-3417ae00-01a9-11eb-9820-d38b12bddddb.png)
