### ISSUE TITLE
more elevations versus volume

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#19]
@VictoriaStarnes See image below from 2-functions.R. 

For the function to convert volume to elevation, the elevations do not do and volumes do not go high enough. the elevation tops out at 68.4 but there can be elevations that exceed that. We need elevations and volumes that go up the max wse for cypress and gauge, should be ~ 69.75 or so.

![image](https://user-images.githubusercontent.com/654215/94368982-c5edc100-00ac-11eb-848b-927033bf7177.png)

**Comment by mcolvin** [comment]
@VictoriaStarnes was working more on calibration and realized this is priority relative to the GAMs. Model calibration is a can get back going once those values are added. Calibration does not depend on the GAMS.

**Comment by VictoriaStarnes** [comment]
I just pushed the updated files. I re-wrote my long script as a for loop so we can update the elevation ranges easier later on if necessary. I also updated the surface area equations as well.
