### ISSUE TITLE
precip data

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#21]
@VictoriaStarnes Is there any precip data, if so can we get that added to the model data? I imagine 30 minute values are not available and we will be working with daily values so we will need to build an approx function to feed daily rainfall with.

**Comment by VictoriaStarnes** [comment]
Precipitation data is not available from the Macon Gauge. The closest gauge with data is PEARL RIVER AT BURNSIDE, MS. This gauge, as well as other nearby gauges, only has daily precipitation data from 2017-2020. Where would you recommend searching for more long term data?

**Comment by mcolvin** [comment]
Look and see if there is anything else local. Might try weather underground or noaa
