### ISSUE TITLE
New effort on DO Model!

### ISSUE THREAD

**Issue by VictoriaStarnes** [mcolvin/Bluff-Lake-Project#23]
!!!!!
I think I have found the issue in the DO model code. If I am reading the code right, our model was predicting change in DO. I was reading dDO as dawn DO not delta DO. So, the issue wasn't really the model, just that we were missing one additional line of code subtracting dDO from dusk_DO. Using this interpretation I was able to change the line that I was worried about back to 60*10^-2 which I think is more realistic . This model also uses the same wind speed coefficient (k) that Miranda's model used. This is the new measured vs. predicted fit:

Check out the CLEAN-DO-Model script and let me know what you think.

![image](https://user-images.githubusercontent.com/45180904/95260185-ec6ad500-07ed-11eb-9c14-5c00bfa0eb00.png)

**Comment by mcolvin** [comment]
That looks great. How does it pan out when looking at various depths? @VictoriaStarnes

**Comment by VictoriaStarnes** [comment]
Plots for variable depths with no change to model:

![image](https://user-images.githubusercontent.com/45180904/95370781-ee40a100-089e-11eb-9288-6238b5e3ac64.png)
![image](https://user-images.githubusercontent.com/45180904/95370793-f3055500-089e-11eb-94fa-0f8a45d72949.png)
![image](https://user-images.githubusercontent.com/45180904/95370813-f8629f80-089e-11eb-972f-f701b6c77c96.png)

Not that you needed to see these plots, but it seems to explain why the shallower points are off. Plots using adjusted k (wind):

![image](https://user-images.githubusercontent.com/45180904/95370981-3364d300-089f-11eb-8aab-7e1a81ef757c.png)
![image](https://user-images.githubusercontent.com/45180904/95370997-38c21d80-089f-11eb-9434-e898a88ac26b.png)
![image](https://user-images.githubusercontent.com/45180904/95371021-3eb7fe80-089f-11eb-9ded-01524badc8f2.png)

**Comment by VictoriaStarnes** [comment]
I added first round of code which will create the DO/Temp/Elevation lookup table. So far I should be able to calculate surface area. I'm running the model on a small data chunk now because the large bathymetric map will take awhile to run. I still need to figure out how to work in a function to allow us to calculate volume. If you want to check it out, the code to run is on lines 1:17, 53:83 of CLEAN-DO-Model.R.

**Comment by mcolvin** [comment]
@VictoriaStarnes  if it is too much to run your computer I can run on Crunch, just get the code setup and that is saves output, test on a couple of iterations in the for loop and then I can set to run the whole thing.

**Comment by VictoriaStarnes** [comment]
I updated the model to incorporate variable depths and adjusted k values. The depths used were the distance from the point measured to the lake bottom. I adjusted k as 0.03*(depth or measurement/total depth) This is the resulting plot:

![image](https://user-images.githubusercontent.com/45180904/95628405-97280100-0a43-11eb-9756-61b174bec838.png)

**Comment by VictoriaStarnes** [comment]
If I manually adjust k(surface) from 0.03 to something like 0.06 it helps shift the slope up a bit..

![image](https://user-images.githubusercontent.com/45180904/95629210-1833c800-0a45-11eb-9c50-fd8c373165b3.png)

**Comment by VictoriaStarnes** [comment]
I have updated the DO model to calculate volume!!! You can check out the CLEAN-DO-Model script. Everything runs, I just need to run the script with all the combos of elevation and temperature over the actual bathymetric map. I was just using a few combos now and running over a smaller list of elevations to make sure everything was set up correctly. I think if I tried to run everything my computer would have a stroke.

**Comment by mcolvin** [comment]
Specify the action needed of me. You need me to run the script right? @VictoriaStarnes

**Comment by VictoriaStarnes** [comment]
Running lines 1:20 and lines 104:152 should run the DO model for the bathymetric map and give us "suitable habitat" volumes for a range of staring DO, temperature, elevation, and fish DO criteria. We still need to discuss the vertical water column segment size that we would like to use to calculate volume. I have used 0.5m segments in the code currently. We also need to discuss optimizing the selection of the starting k value. 

Then the model can be run and this objective metric should be complete. I need help running the model because it would kill my computer.

**Comment by VictoriaStarnes** [comment]
I have completed the script for optimizing k. The minimum value that optimize() spits out is 0.0927 for surface k. Miranda's paper uses 0.03, and I had manually shifted the value to 0.08. So, I think everything is right. Feel free to check my code. Everything that you need to run is in the OptimizingK script that I just pushed. Thanks!

**Comment by mcolvin** [comment]
@VictoriaStarnes Ok. Good. Will check on it asap.

**Comment by mcolvin** [comment]
@VictoriaStarnes I ran CLEAN-DO-Model.R. Got an error. See image below. Fix it up and commit and I will try to run on the server again.

![image](https://user-images.githubusercontent.com/654215/97231818-1e96a380-17aa-11eb-9d30-c7175fe840ed.png)

**Comment by VictoriaStarnes** [comment]
I checked my trimmed back model again, and everything runs correctly. I have now commented out the things that you don't need to run. I tried to run the larger model (with complete bathymetric map) with fewer combinations, but my computer wouldn't finish it, even overnight. It should be correct, but let me know if it's still throwing an error.

**Comment by mcolvin** [comment]
@VictoriaStarnes  ok, looks be running, have it going and it looks to be chugging along. Will let you know as it progresses.

**Comment by mcolvin** [comment]
@VictoriaStarnes  Ran the code--it is super slow. I think you coded up the combos for a short run, only 2 combos were returned. in the for loop add a tracker to know progress, something like `print(i/nrow(combos))`.  

![image](https://user-images.githubusercontent.com/654215/97578445-cbe20500-19be-11eb-8c4b-e08f08eafecc.png)

Looks like combos is only for a small subset.

![image](https://user-images.githubusercontent.com/654215/97578519-e87e3d00-19be-11eb-8cd7-e9b4eb6c1c19.png)

**Comment by VictoriaStarnes** [comment]
I switched to the expanded combos list and added the new code to show progress. It should be ready to run!

**Comment by mcolvin** [comment]
@VictoriaStarnes 

Pull the commit I made that adds some intermediate saving. 
The first combo throws an error in the subset. It returns an empty data.frame. 

![image](https://user-images.githubusercontent.com/654215/97601587-55ea9780-19d8-11eb-8197-2c908a223ded.png)
![image](https://user-images.githubusercontent.com/654215/97601774-892d2680-19d8-11eb-954a-0906f6ee08bf.png)

**Comment by VictoriaStarnes** [comment]
The model code has been edited and shouldn't throw an error! Can you run it when you get the chance?

**Comment by mcolvin** [comment]
Ok, will jump over to Crunch Deuce and see.

@VictoriaStarnes

**Comment by mcolvin** [comment]
@VictoriaStarnes 

Still getting an error.

![image](https://user-images.githubusercontent.com/654215/98045755-9a1dd380-1dee-11eb-83f4-ecc1aad71df7.png)

**Comment by VictoriaStarnes** [comment]
Okay, I just pushed another edit, try that and let me know!

**Comment by mcolvin** [comment]
@VictoriaStarnes   Ok, looks to be running! Will keep an eye on how long this thing might take and report back today.

**Comment by mcolvin** [comment]
@VictoriaStarnes  made it part of the way before it threw an error, see output below. Each sim is taking ~2.5 minutes. With the number of combos that is 36 days to complete. We can run parallel to cut that to 8 days or so, or run both comptuters but before doing that we want to make sure the thing will run fully. It kicked out on combo 6. Let me know what you think.  

![image](https://user-images.githubusercontent.com/654215/98127894-d730a700-1e7c-11eb-8dae-b2e79ef4657a.png)

**Comment by VictoriaStarnes** [comment]
New code has been pushed. I reduced the number of combinations to run over from 25,000 to 2,500 by changing my table layout and how I was saving some of the data. It should be faster now. I also added some code to remove points with depths shallower than 10 cm or points that result in NA values for DO. Try it out and let me know how it goes.

**Comment by mcolvin** [comment]
@VictoriaStarnes made it to 12 this time

![image](https://user-images.githubusercontent.com/654215/98300185-8b662680-1f7e-11eb-95ee-1236d6812951.png)

**Comment by VictoriaStarnes** [comment]
New code pushed give it another shot! 
I ran combos 1:15 and realized that DO was heading in the wrong direction with increasing temperature. I apparently had an incorrect sign in one of the calculations. I went back and corrected that in the original analysis and also updated the optimized k value to reflect those changes.

**Comment by mcolvin** [comment]
@VictoriaStarnes 

Run for 8 hours and at 14%, probably be done in a tomorrow or the next day. 

![image](https://user-images.githubusercontent.com/654215/98687955-ef4a6f80-232f-11eb-9cc7-307d8a939157.png)

**Comment by mcolvin** [comment]
@VictoriaStarnes I think I have it figured out, down from weeks to 3 hours at most...will see what the final timing is, but it should set you up to be able to run on your machine. Will discuss in tomorrow's meeting.

**Comment by mcolvin** [comment]
@VictoriaStarnes Victory! see _do-outputs/combos-fast.csv for results and CLEAN-DO-Model-fast.R to check the code to make sure I didn't mung up what you had. Should be able to compare the first couple rows of 'fast' with the previous outputs we have to make sure they are the same. 

![image](https://user-images.githubusercontent.com/654215/99671288-72a64800-2a37-11eb-9cee-1dbc310310fc.png)

**Comment by VictoriaStarnes** [comment]
Awesome! Thank you, I'll take a look!

**Comment by mcolvin** [comment]
Couple of notes on what I did, 1) I rounded depths, Z to the nearest centimeters, doesn't make much sense in that system to look at mm or smaller, 2) I swapped out a for loop for an lapply didnt get much performance boost but I like it, 3) DO was calculated for just the unique combos of Z2 and k in big_data, and 4) the unique combos were then merged back into big_data. After that everything is the same.
