### ISSUE TITLE
Objective Metrics

### ISSUE THREAD

**Issue by VictoriaStarnes** [mcolvin/Bluff-Lake-Project#24]
I have separated the code that links objective metrics to water elevation. It is saved as a script titled "CLEAN-Objective metrics" found in the analysis folder.

I have saved two outputs from this code as lookup tables. They are saved in the analysis folder and are titled "RawMetrics" and "RescaleMetrics." Within these lookup tables all raw or rescaled metrics conditions are re-iterated for each day of year.

**Comment by mcolvin** [comment]
Is there anything specific I am supposed to do with it? @VictoriaStarnes

**Comment by VictoriaStarnes** [comment]
You told me to add them as an issue when we talked yesterday. We still need to incorporate seasonality into these tables to make day of year significant. I figured we could talk about how we would like to do that in today's meeting.
