### ISSUE TITLE
function?

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#26]
@VictoriaStarnes 

where is the function EL_2_Vol pulled from in CLEAN-Objective metrics new.R? Line 248

![image](https://user-images.githubusercontent.com/654215/106789034-58800d00-6617-11eb-9a88-2b2349791e93.png)

**Comment by VictoriaStarnes** [comment]
It's on line 74 of the 2-functions.R script. You have to run that file first.
