### ISSUE TITLE
Running the 6.5-analysis-hour-edt-all-elevations.R script

### ISSUE THREAD

**Issue by VictoriaStarnes** [mcolvin/Bluff-Lake-Project#27]
The DO model finally finished running. So all the supporting files should be up to date.

 I also sourced the files that you need within the 6.5-analysis-hour-edt-all-elevations.R script. I moved some files around and changed the code so the working directory just needs to be set as the bluff-lake-model folder. 

Let me know how it goes!

**Comment by mcolvin** [comment]
Done, out see
\_analysis\bluff-lake-model\_outputs\final.csv for the summarized data.
