### ISSUE TITLE
Loop Issue

### ISSUE THREAD

**Issue by VictoriaStarnes** [mcolvin/Bluff-Lake-Project#5]
There is an issue with the for-loop in the combined_annotated_analysis_period.Rmd on line 397. I replaced the year-month combinations with year-period combinations. This should be a simple change, but running the for-loop results in the error "replacement has length zero." Running line 397 results in a single value, not a vector, so I know the problem is there, but I am unsure how to fix it.

**Comment by mcolvin** [comment]
@VictoriaStarnes  there is only 1 day in the dataset for 1951-8 that is the error. Can't loop over 2... since there is only 1 row of data
![image](https://user-images.githubusercontent.com/654215/82094107-092d3180-96c2-11ea-9155-375945d5014b.png)
See code uploaded to github.
