### ISSUE TITLE
level logger data for other sites

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#6]
@VictoriaStarnes  Do we have other level logger data for that emergency outlet location before it was removed? If so can you get it compiled so I can add it to the bluff lake model calibration if needed.

**Comment by VictoriaStarnes** [comment]
We have logger data from the location on the levee from 5/7/19/-11/9/19. I replaced that logger and the current data spans 1/24/20-5/12/20. I have added this information to the repository. I have additional data to process and upload for the logger on the Noxubee side, as well as more recent data for all loggers. I will get that data uploaded tomorrow.
