### ISSUE TITLE
lake elevations

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#8]
@VictoriaStarnes 

I was wrangling the data a bit and I plotted the lake elevations for the cypress logger and the intake and they were ~0.5 difference between them. I expected them to be darn close to each other. See figure below. Why are they so different? Way to fix?

![image](https://user-images.githubusercontent.com/654215/87231798-c618d300-c37f-11ea-8ecf-ac448947fb66.png)

**Comment by VictoriaStarnes** [comment]
Water elevation near the intake was actually 0.5m higher on the Noxubee side. Water from the river goes over a stack of boards in the control structure into a concrete water detention box. That box has 2-3 culverts that empty out into Bluff Lake, usually below lake elevation.

**Comment by mcolvin** [comment]
Oh ok, got my wires crossed on where it was and thinking it was the logger on the levee road.

Don’t we also have elevation data for the logger on the road too? Can’t recall if you sent that yet or added it to the repo.

**Comment by VictoriaStarnes** [comment]
Yes all of the logger data should be pushed. The location label should be "Gauge"

**Comment by mcolvin** [comment]
Not finding it. What is the file and directory?

**Comment by VictoriaStarnes** [comment]
Sorry about that. Those records are under _analysis in the access database in the Level_logger table.

**Comment by mcolvin** [comment]
ok, got em.
