### ISSUE TITLE
add function for WSE and volume

### ISSUE THREAD

**Issue by mcolvin** [mcolvin/Bluff-Lake-Project#9]
@VictoriaStarnes Can you add a function to the repo to 2-functions.R that will take volume as an input and return water surface elevation?

**Comment by mcolvin** [comment]
Also-can you hard code into 3-load-and-clean.R
* the elevation of the emergency spillway and the width
* widths for each bay in the wcs

**Comment by VictoriaStarnes** [comment]
Made the changes and pushed the updated files!
